server.port=8083

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/event_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=event_user
spring.datasource.password=event_password

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

#config eureka client
spring.application.name=eureka-client
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
