#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

server.port=8082
# H2
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.datasource.generate-unique-name=false
spring.datasource.name=ArticleDatabase
spring.datasource.url=jdbc:h2:file:C:/Users/HP/Desktop/Applications web distribuées/ArticleDatabase/Article
spring.h2.console.path=/h2
# Datasource
spring.datasource.username=amine
spring.datasource.password=amine7
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = update



#config eureka client
spring.application.name=eureka-client
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#config eureka client







