apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server-app
  template:
    metadata:
      labels:
        app: eureka-server-app
    spec:
      containers:
        - name: eureka-app-container
          image: aminebarguellil/discovery-service